name: Push Laravel and Node.js Images To DockerHub Then Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  Build-Laravel-And-Push-Dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Laravel Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/laravel_electron:latest .

      - name: Push Laravel Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/laravel_electron:latest

  Build-NodeJS-And-Push-Dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Node.js Docker image
        run: docker build -f Dockerfile-node -t ${{ secrets.DOCKER_USERNAME }}/nodejs_chat:latest ./chat_server

      - name: Push Node.js Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nodejs_chat:latest

  Deploy-To-EC2:
    needs: [Build-Laravel-And-Push-Dockerhub, Build-NodeJS-And-Push-Dockerhub]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker-compose down
            docker rmi ${{ secrets.DOCKER_USERNAME }}/laravel_electron:latest
            docker rmi ${{ secrets.DOCKER_USERNAME }}/nodejs_chat:latest
            docker-compose up -d