name: Run Laravel Tests

on:
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install PHP dependencies and setup Laravel
        working-directory: ./imagesElectron
        run: |
          cp .env.testing .env
          cat .env.testing 
          cat .env         
          composer install --prefer-dist --no-progress
          php artisan key:generate
          php artisan jwt:secret --force
          php artisan migrate
          cat .env.testing  
          cat .env          
          cp .env .env.testing

      - name: Run Laravel tests
        working-directory: ./imagesElectron
        run: php artisan test
